services:
- docker

language: ruby
cache: bundler
sudo: false
rvm:
- 2.5.3

bundler_args: "--without kitchen_vagrant"

before_install:
- gem update --system
- gem install bundler

script: bundle exec kitchen test ${INSTANCE} --destroy=always

env:
  global:
  - KITCHEN_YAML=.kitchen.docker.yml
  matrix:
  - INSTANCE=chef-14-ubuntu-1804-docker
  - INSTANCE=chef-14-ubuntu-1604-docker
  - INSTANCE=chef-14-ubuntu-1404-docker
  - INSTANCE=chef-14-debian-9-docker
  - INSTANCE=chef-14-debian-8-docker
  - INSTANCE=chef-14-centos-7-docker
  - INSTANCE=chef-14-centos-6-docker
  - INSTANCE=chef-13-ubuntu-1804-docker
  - INSTANCE=chef-13-ubuntu-1604-docker
  - INSTANCE=chef-13-ubuntu-1404-docker
  - INSTANCE=chef-13-debian-9-docker
  - INSTANCE=chef-13-debian-8-docker
  - INSTANCE=chef-13-centos-7-docker
  - INSTANCE=chef-13-centos-6-docker
jobs:
  include:
  - stage: lint
    script:
    - bundle exec rubocop --version
    - bundle exec rubocop
    - bundle exec foodcritic --version
    - bundle exec foodcritic --contex --epic-fail any .
    - bundle exec rspec -fd test/cookbooks/testrig/spec/chefspec.rb
  - stage: deploy
    if: tag =~ ^[0-9]+\.[0-9]+\.[0-9]+$
    script:
    - openssl aes-256-cbc -K $encrypted_e35c8607da72_key -iv $encrypted_e35c8607da72_iv -in .travis/client.pem.enc -out .travis/client.pem -d
    - bundle exec stove login --username dr_agon --key .travis/client.pem
    - bundle exec stove --no-git
